# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'story_eq_loads.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1124, 475)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 361, 211))
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(9, 19, 341, 181))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.short_period_spectral = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.short_period_spectral.setPlaceholderText("")
        self.short_period_spectral.setObjectName("short_period_spectral")
        self.verticalLayout_2.addWidget(self.short_period_spectral)
        self.one_second_period_spectral = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.one_second_period_spectral.setObjectName("one_second_period_spectral")
        self.verticalLayout_2.addWidget(self.one_second_period_spectral)
        self.corner_period_small_spectral = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.corner_period_small_spectral.setReadOnly(True)
        self.corner_period_small_spectral.setObjectName("corner_period_small_spectral")
        self.verticalLayout_2.addWidget(self.corner_period_small_spectral)
        self.corner_peiod_big_spectral = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.corner_peiod_big_spectral.setReadOnly(True)
        self.corner_peiod_big_spectral.setObjectName("corner_peiod_big_spectral")
        self.verticalLayout_2.addWidget(self.corner_peiod_big_spectral)
        self.period_structure_X_direct = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.period_structure_X_direct.setObjectName("period_structure_X_direct")
        self.verticalLayout_2.addWidget(self.period_structure_X_direct)
        self.period_structure_Y_direct = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.period_structure_Y_direct.setObjectName("period_structure_Y_direct")
        self.verticalLayout_2.addWidget(self.period_structure_Y_direct)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setGeometry(QtCore.QRect(410, 10, 241, 211))
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 221, 181))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.spectrum_graphic = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.spectrum_graphic.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.spectrum_graphic.setContentsMargins(0, 0, 0, 0)
        self.spectrum_graphic.setObjectName("spectrum_graphic")
        self.groupBox_3 = QtWidgets.QGroupBox(Form)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 230, 641, 151))
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(10, 20, 189, 119))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.number_stories_lineedit = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.number_stories_lineedit.setObjectName("number_stories_lineedit")
        self.verticalLayout_3.addWidget(self.number_stories_lineedit)
        spacerItem = QtWidgets.QSpacerItem(10, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout_3.addItem(spacerItem)
        self.sum_stories_weight_lineEdit = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.sum_stories_weight_lineEdit.setObjectName("sum_stories_weight_lineEdit")
        self.verticalLayout_3.addWidget(self.sum_stories_weight_lineEdit)
        self.label_7 = QtWidgets.QLabel(self.horizontalLayoutWidget_2)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_3.addWidget(self.label_7)
        self.horizontalLayout_2.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.number_stories = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.number_stories.setObjectName("number_stories")
        self.verticalLayout_4.addWidget(self.number_stories)
        self.story_info_button = QtWidgets.QPushButton(self.horizontalLayoutWidget_2)
        self.story_info_button.setObjectName("story_info_button")
        self.verticalLayout_4.addWidget(self.story_info_button)
        self.sum_structure_weight = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.sum_structure_weight.setReadOnly(True)
        self.sum_structure_weight.setObjectName("sum_structure_weight")
        self.verticalLayout_4.addWidget(self.sum_structure_weight)
        self.sum_structure_height = QtWidgets.QLineEdit(self.horizontalLayoutWidget_2)
        self.sum_structure_height.setReadOnly(True)
        self.sum_structure_height.setObjectName("sum_structure_height")
        self.verticalLayout_4.addWidget(self.sum_structure_height)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.horizontalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox_3)
        self.horizontalLayoutWidget_3.setGeometry(QtCore.QRect(210, 20, 341, 121))
        self.horizontalLayoutWidget_3.setObjectName("horizontalLayoutWidget_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_3)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_8 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_5.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_9.setObjectName("label_9")
        self.verticalLayout_5.addWidget(self.label_9)
        self.label_10 = QtWidgets.QLabel(self.horizontalLayoutWidget_3)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_5.addWidget(self.label_10)
        self.horizontalLayout_3.addLayout(self.verticalLayout_5)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.EQL_reduce_coeff_X_direct = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.EQL_reduce_coeff_X_direct.setObjectName("EQL_reduce_coeff_X_direct")
        self.verticalLayout_6.addWidget(self.EQL_reduce_coeff_X_direct)
        self.EQL_reduce_coeff_Y_direct = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.EQL_reduce_coeff_Y_direct.setObjectName("EQL_reduce_coeff_Y_direct")
        self.verticalLayout_6.addWidget(self.EQL_reduce_coeff_Y_direct)
        self.struct_important_coeff = QtWidgets.QLineEdit(self.horizontalLayoutWidget_3)
        self.struct_important_coeff.setObjectName("struct_important_coeff")
        self.verticalLayout_6.addWidget(self.struct_important_coeff)
        self.horizontalLayout_3.addLayout(self.verticalLayout_6)
        self.calculate_button = QtWidgets.QPushButton(self.groupBox_3)
        self.calculate_button.setGeometry(QtCore.QRect(560, 110, 81, 28))
        self.calculate_button.setObjectName("calculate_button")
        self.groupBox_4 = QtWidgets.QGroupBox(Form)
        self.groupBox_4.setGeometry(QtCore.QRect(10, 380, 641, 80))
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.horizontalLayoutWidget_4.setGeometry(QtCore.QRect(9, 30, 541, 31))
        self.horizontalLayoutWidget_4.setObjectName("horizontalLayoutWidget_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_4)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_11 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_5.addWidget(self.label_11)
        self.verticalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_4.addLayout(self.verticalLayout_7)
        self.base_shear_load_X_direct = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.base_shear_load_X_direct.setReadOnly(True)
        self.base_shear_load_X_direct.setObjectName("base_shear_load_X_direct")
        self.horizontalLayout_4.addWidget(self.base_shear_load_X_direct)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_12 = QtWidgets.QLabel(self.horizontalLayoutWidget_4)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_6.addWidget(self.label_12)
        self.base_shear_load_Y_direct = QtWidgets.QLineEdit(self.horizontalLayoutWidget_4)
        self.base_shear_load_Y_direct.setReadOnly(True)
        self.base_shear_load_Y_direct.setObjectName("base_shear_load_Y_direct")
        self.horizontalLayout_6.addWidget(self.base_shear_load_Y_direct)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_6)
        self.groupBox_5 = QtWidgets.QGroupBox(Form)
        self.groupBox_5.setGeometry(QtCore.QRect(660, 10, 451, 211))
        self.groupBox_5.setObjectName("groupBox_5")
        self.list_X = QtWidgets.QListWidget(self.groupBox_5)
        self.list_X.setGeometry(QtCore.QRect(10, 20, 431, 181))
        self.list_X.setObjectName("list_X")
        self.groupBox_6 = QtWidgets.QGroupBox(Form)
        self.groupBox_6.setGeometry(QtCore.QRect(660, 230, 451, 231))
        self.groupBox_6.setObjectName("groupBox_6")
        self.list_Y = QtWidgets.QListWidget(self.groupBox_6)
        self.list_Y.setGeometry(QtCore.QRect(10, 30, 431, 181))
        self.list_Y.setObjectName("list_Y")
        self.draw_graphic = QtWidgets.QPushButton(Form)
        self.draw_graphic.setGeometry(QtCore.QRect(380, 40, 21, 28))
        self.draw_graphic.setObjectName("draw_graphic")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Katlara Etkiyen Deprem Yüklerinin Hesabı"))
        self.groupBox.setTitle(_translate("Form", "Periyot Bilgileri"))
        self.label.setText(_translate("Form", "Kısa periyot tasarım spektral ivme katsayısı"))
        self.label_2.setText(_translate("Form", "1 s periyot tasarım spektral ivme katsayısı"))
        self.label_3.setText(_translate("Form", "Grafik Köşe Periyodu T_A"))
        self.label_4.setText(_translate("Form", "Gafik Köşe Periyodu T_B"))
        self.label_5.setText(_translate("Form", "X Doğrultusu Bina Hakim Periyodu"))
        self.label_6.setText(_translate("Form", "Y Doğrultusu Bina Hakim Periyodu"))
        self.groupBox_2.setTitle(_translate("Form", "Spektrum Grafiği"))
        self.groupBox_3.setTitle(_translate("Form", "Bina Bilgileri"))
        self.number_stories_lineedit.setText(_translate("Form", "Kat Adedi"))
        self.sum_stories_weight_lineEdit.setText(_translate("Form", "Bina Ağırlığı"))
        self.label_7.setText(_translate("Form", "Bina Yüksekliği"))
        self.story_info_button.setText(_translate("Form", "Giriş"))
        self.label_8.setText(_translate("Form", "X doğrultusu deprem yükü azaltma katsayısı"))
        self.label_9.setText(_translate("Form", "Y doğrultusu deprem yükü azaltma katsayısı"))
        self.label_10.setText(_translate("Form", "Bina Önem Katsayısı"))
        self.calculate_button.setText(_translate("Form", "Hesapla"))
        self.groupBox_4.setTitle(_translate("Form", "Eşdeğer Deprem Yükü Yöntemine Göre Hesaplanan Taban Kesme Kuvvetleri (kNm)"))
        self.label_11.setText(_translate("Form", "X doğrultusu için Vt :"))
        self.label_12.setText(_translate("Form", "Y doğrultusu için Vt :"))
        self.groupBox_5.setTitle(_translate("Form", "X doğrultusunda katlara etkiyen deprem yükleri (kN)"))
        self.groupBox_6.setTitle(_translate("Form", "Y doğrultusunda katlara etkiyen deprem yükeleri (kN)"))
        self.draw_graphic.setText(_translate("Form", "->"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

